version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    restart: always
    command: gunicorn news_site.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    expose:
      - 8000

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/freelance.com.kz.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - web


volumes:
  static:
  media:
